const ListOfBooks = [
    {
        id: 1,
        NameOfBook: "",
        fontFamily: "",
        className:"imgListOfBooks",
        imgOfProject: require("../img/imgToListOfBooks/metro2033.jpg"),
        linkToBook: "https://youtu.be/t3217H8JppI",
    },
    {
        id: 2,
        NameOfBook: "",
        fontFamily: "",
        className:"imgListOfBooksSmall",
        imgOfProject: require("../img/imgToListOfBooks/future.jpg"),
        linkToBook: "https://www.youtube.com/watch?v=7z4vhRymsIY&list=PLAC65E2BA46384D13&index=1",
    },
    {
        id: 3,
        NameOfBook: "",
        fontFamily: "",
        className:"imgListOfBooksSmall",
        imgOfProject: require("../img/imgToListOfBooks/tekst.jpg"),
        linkToBook: "https://www.youtube.com/watch?v=7jLEpQlF3IY&list=OLAK5uy_kUvFwuWeGN8QyBrQV9e_O1iM60KY3GC5I&index=2&t=0s",
    },
    {
        id: 4,
        NameOfBook: "",
        fontFamily: "",
        className:"imgListOfBooksSmall",
        imgOfProject: require("../img/imgToListOfBooks/HowToWinFriends.jpg"),
        linkToBook: "https://www.youtube.com/watch?v=OjS6w62GObw&list=PLPsiHorJo2qyGv5wgWGiBEiRI1H-acykd",
    },
    {
        id: 5,
        NameOfBook: "",
        fontFamily: "",
        className:"imgListOfBooksSmall",
        imgOfProject: require("../img/imgToListOfBooks/gameOfThrones.jpg"),
        linkToBook: "https://www.youtube.com/watch?v=ltH9IgyZKbw&list=PL_Ed-YblFpnZy-k3iOtksrpOLUZcXHHbW",
    },
    {
        id: 6,
        NameOfBook: "",
        fontFamily: "",
        className:"imgListOfBooksSmall",
        imgOfProject: require("../img/imgToListOfBooks/hobbit.jpg"),
        linkToBook: "https://www.youtube.com/watch?v=ltH9IgyZKbw&list=PL_Ed-YblFpnZy-k3iOtksrpOLUZcXHHbW",
    },
    {
        id: 7,
        NameOfBook: "",
        fontFamily: "",
        className:"imgListOfBooks",
        imgOfProject: require("../img/imgToListOfBooks/richDad.jpg"),
        linkToBook: "https://www.youtube.com/watch?v=ltH9IgyZKbw&list=PL_Ed-YblFpnZy-k3iOtksrpOLUZcXHHbW",
    },
    {
        id: 8,
        NameOfBook: "",
        fontFamily: "",
        className:"imgListOfBooksSmall",
        imgOfProject: require("../img/imgToListOfBooks/DonaldChuck.jpg"),
        linkToBook: "https://www.youtube.com/watch?v=ltH9IgyZKbw&list=PL_Ed-YblFpnZy-k3iOtksrpOLUZcXHHbW",
    },
    {
        id: 9,
        NameOfBook: "",
        fontFamily: "",
        className:"imgListOfBooksSmall",
        imgOfProject: require("../img/imgToListOfBooks/starwars.jpg"),
        linkToBook: "https://www.youtube.com/watch?v=ltH9IgyZKbw&list=PL_Ed-YblFpnZy-k3iOtksrpOLUZcXHHbW",
    },
    {
        id: 10,
        NameOfBook: "",
        fontFamily: "",
        className:"imgListOfBooksSmall",
        imgOfProject: require("../img/imgToListOfBooks/starwarsPathOfDest.jpg"),
        linkToBook: "https://www.youtube.com/watch?v=ltH9IgyZKbw&list=PL_Ed-YblFpnZy-k3iOtksrpOLUZcXHHbW",
    }
]

export default ListOfBooks;